all: dora frontier randomwalk

dora: dora.bzz
	bzzc -I /usr/local/share/buzz/include dora.bzz

frontier: frontier.bzz
	bzzc -I /usr/local/share/buzz/include frontier.bzz

randomwalk: randomwalk.bzz
	bzzc -I /usr/local/share/buzz/include randomwalk.bzz

clean:
	rm ./*.bdb ./*.bo